# Generated by Django 2.2.7 on 2019-12-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255)),
                ('psswrd', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('psswrd', models.CharField(max_length=255)),
                ('p_bio', models.CharField(max_length=500)),
                ('p_status', models.CharField(blank=True, max_length=7, null=True)),
                ('pers_pic', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Crew',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrewRes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Crew_Res',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrewSpec',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Crew_Spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mod_name', models.CharField(max_length=255)),
                ('mod_description', models.CharField(max_length=500)),
                ('mod_status', models.CharField(blank=True, max_length=7, null=True)),
                ('mod_pic', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Modules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('n_date', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'News',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('s_mail', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Newsletter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('r_topic', models.CharField(max_length=50)),
                ('r_status', models.CharField(max_length=13)),
                ('prop_name', models.CharField(max_length=30)),
                ('prop_mail', models.CharField(max_length=50)),
                ('r_message', models.CharField(max_length=800)),
            ],
            options={
                'db_table': 'Research',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResSpec',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Res_Spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sp_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Specializations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T500',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 't500',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tourism',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=30)),
                ('personal', models.IntegerField(blank=True, null=True)),
                ('t_mail', models.CharField(max_length=50)),
                ('t_message', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Tourism',
                'managed': False,
            },
        ),
    ]
